version: '3.9'
services:
  teamie-app:
    container_name: teamie-prod
    image: teamie-prod:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: always