export enum ErrorCode {
    //공통
    BAD_REQUEST = 'COMMON400',
    UNAUTHORIZED = 'COMMON401',
    INTERNAL_SERVER_ERROR = 'COMMON500',
    //사용자
    USER_NOT_FOUND = 'USER404',
    USER_INVARIANT_VIOLATION = 'AUTH5001',
    //프로젝트
    INVALID_INVITE_CODE = 'PROJECT4011',
    FORBIDDEN_USER_FOR_PROJECT = 'PROJECT4031',
    FORBIDDEN_USER_FOR_UPDATE = 'PROJECT4032',
    PROJECT_ALREADY_COMPLETED = 'PROJECT4033',
    FORBIDDEN_SELF_ASSIGN = 'PROJECT4034',
    NOT_POST_AUTHOR = 'PROJECT4035',
    NOT_YOUR_PROFILE = 'PROJECT4036',
    PROJECT_NOT_FOUND = 'PROJECT4041',
    POST_NOT_FOUND = 'PROJECT4042',
    POSTS_EXCEEDED = 'PROJECT4091',
    ALREDY_LEADER = 'PROJECT4092',
    ASSIGNEE_NOT_MEMBER = 'PROJECT4093',
    POST_NOT_PARSED = 'PROJECT5001',
    PROJECT_TRANSACTION_ERROR = 'PROJECT5002',
    //업무
    TASK_NOT_FOUND = 'TASK4041',
    TASK_FILE_NOT_FOUND = 'TASKFILE4042',
    //개인회고
    PERSONAL_RECALL_NOT_FOUND = 'PERSONALRECALL4041',
    //스텝
    STEP_DELETE_FORBIDDEN = 'STEP4031',
    STEP_NOT_FOUND = 'STEP4041',
    //일정
    PLAN_NOT_FOUND = 'PLAN4041',
    //마스터 포트폴리오
    MASTER_PORTFOLIO_NOT_FOUND = 'MASTERPORTFOLIO4041',
    MASTER_PORTFOLIO_DUPLICATE = 'MASTERPORTFOLIO4091',
    MASTER_PORTFOLIO_AI_NOT_FOUND = 'MASTERPORTFOLIOAI4041',
    //댓글
    COMMENT_NOT_FOUND = 'COMMENT4041',
    FORBIDDEN_COMMENT_FOR_UPDATE = 'COMMENT4031',
    // LLM
    PROMPT_LOADING_ERROR = 'LLM5001',
}
