export enum ErrorCode {
    //공통
    BAD_REQUEST='COMMON400',
    UNAUTHORIZED='COMMON401',
    INTERNAL_SERVER_ERROR='COMMON500',
    //사용자
    USER_INVARIANT_VIOLATION='AUTH5001',
    //프로젝트
    INVALID_INVITE_CODE='PROJECT4011',
    FORBIDDEN_USER_FOR_PROJECT='PROJECT4031',
    FORBIDDEN_USER_FOR_UPDATE='PROJECT4032',
    PROJECT_ALREADY_COMPLETED='PROJECT4033',
    PROJECT_NOT_FOUND='PROJECT4041',
    //업무
    TASK_NOT_FOUND='TASK4041',

    //스텝
    STEP_NOT_FOUND='STEP4041',
}